-- MySQL Script generated by MySQL Workbench
-- 04/12/16 17:27:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blackjack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blackjackjbm` DEFAULT CHARACTER SET latin1 ;
USE `blackjackjbm` ;

-- -----------------------------------------------------
-- Table `blackjack`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blackjackjbm`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_name` VARCHAR(24) NOT NULL COMMENT '',
  `user_hash_pass` VARCHAR(255) NOT NULL COMMENT '',
  `user_balance` INT(11) NOT NULL DEFAULT '1000' COMMENT '',
  `user_active` TINYINT(1) NOT NULL COMMENT '',
  `user_failed_log_attempts` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blackjack`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blackjackjbm`.`games` (
  `game_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  `start_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `end_time` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `number_decks` INT(2) NOT NULL DEFAULT '1' COMMENT '',
  `user_starting_balance` INT(12) NOT NULL COMMENT '',
  `user_bet_amount` INT(12) NOT NULL COMMENT '',
  PRIMARY KEY (`game_id`)  COMMENT '',
  INDEX `fk_user_table_id_for_game_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_table_id_for_game`
    FOREIGN KEY (`user_id`)
    REFERENCES `blackjack`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blackjack`.`games_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blackjackjbm`.`games_meta` (
  `meta_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `game_id` INT(11) NOT NULL COMMENT '',
  `metaKey` VARCHAR(255) NOT NULL COMMENT '',
  `metaValue` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`meta_id`)  COMMENT '',
  INDEX `fk_game_table_id_idx` (`game_id` ASC)  COMMENT '',
  CONSTRAINT `fk_game_table_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `blackjack`.`games` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blackjack`.`users_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blackjackjbm`.`users_meta` (
  `meta_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  `total_bet` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `total_won` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `total_hands` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `hands_won` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `blackjacks` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`meta_id`)  COMMENT '',
  INDEX `fk_user_table_id_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_table_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `blackjack`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
